### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by janezlapajne** [mareksubocz/TrackNet#2]
Hello, nice work! Is it possible to provide a sample dataset to quickly test whether everything works as expected? Many thanks!

**Comment by mareksubocz** [comment]
Sure, I will provide it soon, in the meantime you can use [labellingTool.py](https://github.com/mareksubocz/TrackNet/blob/main/labellingTool.py) to get the .csv file and put it in folders like so:

    dataset                   # Root dataset folder   
    ├── videos                # Folder containing video files
    │   ├── vid1.mp4
    │   ├── vid2.mp4          
    │   └── ...         
    └── csvs                  # Folder containing csv annotations
        ├── vid1.csv
        ├── vid2.csv          
        └── ...

Or, in the case of image dataset:

    dataset                       # Root dataset folder   
    ├── images                    # Folder containing videos folders
    │   ├── vid1.mp4                   # Folder containing vid1.mp4 split to frames 
    │   │   ├── 00001.jpg. 
    │   │   ├── 00002.jpg. 
    │   │   └── ...         
    │   └── vid2   
    │       └── ...              
    └── csvs                      # Folder containing csv annotations
        ├── vid1.csv          
        └── vid2.csv

I will try to provide an example dataset shortly, in the meantime let me know if everything works and leave a star if you like it :)

**Comment by janezlapajne** [comment]
Nice, thanks! I will get back to you when I receive a video. I will definitely let you know if anything does not work, do not worry about that 😁. Of course, I starred the project already since you deserve it. I believe that the training recipe you have provided follows the same approach from the original article? Also, do you maybe know whether the authors of the paper also provide the datasets on which the network was trained? Anyways, thanks and please, let me know when the dataset will be ready 💯.

**Comment by mareksubocz** [comment]
Example datasets are ready :)
01caceb2c59d2b97fa18fa2e90fd4e4db87a7610

**Comment by janezlapajne** [comment]
Thanks for the replay. However, we somehow switch the plans, so we will probably use label studio for image segmentation, which can output multiple formats. Can your network be trained by default on coco dataset?

**Comment by mareksubocz** [comment]
No, but if you load your new dataset using [fiftyone](https://docs.voxel51.com/), I have a [script](https://github.com/mareksubocz/Beaver/blob/master/converters/SuperviselyToFiftyoneToX.ipynb) ready to convert it back to standard format.

If you decide on converting coco -> tracknet yourself:
1. let me know, I could probably help
2. make a PR adding it to my repo if you do it yourself
3. if you add 'h' and 'w' columns (height and width) to csvs, the circle will be shaped more like the original object.
