### ISSUE TITLE
Predict issue.

### ISSUE THREAD

**Issue by pantongwang** [mareksubocz/TrackNet#5]
How to predict video and just outputs a video. I run this project on Google Colab, and no needs to look predict process. Pls.

**Comment by mareksubocz** [comment]
look at [predict.py](https://github.com/mareksubocz/TrackNet/blob/main/predict.py) in function [get_ball_position](https://github.com/mareksubocz/TrackNet/blob/main/predict.py#L8). it uses opencv contours to find the biggest one and output it's coordinates. Is it what you asked for?

**Comment by pantongwang** [comment]
I don't need the window page when predicting videos. How can I modify the code to output predicted videos directly?

**Comment by mareksubocz** [comment]
remove [this part](https://github.com/mareksubocz/TrackNet/blob/main/predict.py#LL83C1-L85C46) to stop displaying the video. if by "output predicted videos" you mean save it to file, use [VideoWriter](https://www.geeksforgeeks.org/saving-a-video-using-opencv/)
